/*
"Generated by OpenAI's chatGPT" - w/ modifications
*/
package controller

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/TimetoPretend54/go-chatgpt-copilot/model"
	"github.com/TimetoPretend54/go-chatgpt-copilot/service/mock"
	"github.com/labstack/echo/v4"
)

func TestGetDog(t *testing.T) {
	t.Logf("test TestGetDog")
	e := echo.New()
	req := httptest.NewRequest(http.MethodGet, "/", nil)
	rec := httptest.NewRecorder()
	c := e.NewContext(req, rec)
	mockAnimalService := &mock.AnimalService{
		ExpectedOutput: "test",
		ExpectedErr:    nil,
	}
	dogCtl := DogController{Service: mockAnimalService}

	if err := dogCtl.GetDog(c); err != nil {
		t.Errorf("TestGetDog: %s", err)
	}

	if rec.Code != http.StatusOK {
		t.Errorf("TestGetDog: expected status %d, got %d", http.StatusOK, rec.Code)
	}
}

func TestAddDog(t *testing.T) {
	t.Logf("test TestAddDog")
	e := echo.New()
	dog := model.Dog{
		Name:  "Tom",
		Breed: "Beagle",
		Age:   3,
	}
	req := httptest.NewRequest(http.MethodPost, "/", nil)
	req.Header.Set(echo.HeaderContentType, echo.MIMEApplicationJSON)
	rec := httptest.NewRecorder()
	c := e.NewContext(req, rec)
	c.Set("request", dog)

	mockAnimalService := &mock.AnimalService{
		ExpectedOutput: "test",
		ExpectedErr:    nil,
	}
	dogCtl := DogController{Service: mockAnimalService}

	if err := dogCtl.AddDog(c); err != nil {
		t.Errorf("TestAddDog: %s", err)
	}

	if rec.Code != http.StatusOK {
		t.Errorf("TestAddDog: expected status %d, got %d", http.StatusOK, rec.Code)
	}
}
