/*
"Generated by OpenAI's chatGPT" - w/ modifications
*/
package handler

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/TimetoPretend54/go-chatgpt-copilot/model"
	"github.com/labstack/echo/v4"
)

func TestGetCat(t *testing.T) {
	t.Logf("test TestGetCat")
	e := echo.New()
	req := httptest.NewRequest(http.MethodGet, "/", nil)
	rec := httptest.NewRecorder()
	c := e.NewContext(req, rec)

	if err := GetCat(c); err != nil {
		t.Errorf("TestGetCat: %s", err)
	}

	if rec.Code != http.StatusOK {
		t.Errorf("TestGetCat: expected status %d, got %d", http.StatusOK, rec.Code)
	}
}

func TestAddCat(t *testing.T) {
	t.Logf("test TestAddCat")
	e := echo.New()
	cat := model.Cat{
		Name:  "Tom",
		Breed: "Siamese",
		Age:   3,
	}
	req := httptest.NewRequest(http.MethodPost, "/", nil)
	req.Header.Set(echo.HeaderContentType, echo.MIMEApplicationJSON)
	rec := httptest.NewRecorder()
	c := e.NewContext(req, rec)
	c.Set("request", cat)

	if err := AddCat(c); err != nil {
		t.Errorf("TestAddCat: %s", err)
	}

	if rec.Code != http.StatusOK {
		t.Errorf("TestAddCat: expected status %d, got %d", http.StatusOK, rec.Code)
	}
}
