/*
"Generated by OpenAI's chatGPT" - w/ modifications
*/
package middleware

import (
	"time"

	"github.com/labstack/echo/v4"
)

// Logger middleware logs incoming requests
func Logger() echo.MiddlewareFunc {
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			start := time.Now()
			if err := next(c); err != nil {
				c.Error(err)
			}
			println(c.Request().Method, c.Request().URL, time.Since(start))
			return nil
		}
	}
}
