/*
"Generated by OpenAI's chatGPT" - w/ modifications
*/
package api

import (
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

// LoadAnimalRoutes adds animal related routes to the provided Echo instance
func (dc *DependencyContainer) LoadAnimalRoutes(e *echo.Echo) {

	// Animal routes group
	animalGroup := e.Group("/animals")
	animalGroup.Use(middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins: []string{"*"},
		AllowMethods: []string{http.MethodGet, http.MethodPut, http.MethodPost, http.MethodDelete},
	}))

	// Dog routes
	animalGroup.GET("/dog", dc.DogCtl.GetDog)
	animalGroup.GET("/dogs", dc.DogCtl.GetDogs)
	animalGroup.GET("/dogs/:name", dc.DogCtl.GetDogByName)
	animalGroup.POST("/dogs", dc.DogCtl.AddDog)

	// Cat routes
	animalGroup.GET("/cat", dc.CatCtl.GetCat)
	animalGroup.GET("/cats", dc.CatCtl.GetCats)
	animalGroup.GET("/cats/:name", dc.CatCtl.GetCatByName)
	animalGroup.POST("/cats", dc.CatCtl.AddCat)

	// Swagger routes (on Windows, able to use "/assets/swaggerapi", but not on linux")
	e.Static("/swagger", "assets/swaggerapi")
}
