/*
"Generated by OpenAI's chatGPT" - w/ modifications
*/
package api

import (
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"

	"github.com/TimetoPretend54/go-chatgpt-copilot/api/handler"
)

// LoadAnimalRoutes adds animal related routes to the provided Echo instance
func LoadAnimalRoutes(e *echo.Echo) {

	// Animal routes group
	animalGroup := e.Group("/animals")
	animalGroup.Use(middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins: []string{"*"},
		AllowMethods: []string{http.MethodGet, http.MethodPut, http.MethodPost, http.MethodDelete},
	}))

	// Dog routes
	animalGroup.GET("/dog", handler.GetDog)
	animalGroup.GET("/dogs", handler.GetDogs)
	animalGroup.GET("/dogs/:name", handler.GetDogByName)
	animalGroup.POST("/dogs", handler.AddDog)

	// Cat routes
	animalGroup.GET("/cat", handler.GetCat)
	animalGroup.GET("/cats", handler.GetCats)
	animalGroup.GET("/cats/:name", handler.GetCatByName)
	animalGroup.POST("/cats", handler.AddCat)

	// Swagger routes (on Windows, able to use "/assets/swaggerapi", but not on linux")
	e.Static("/swagger", "assets/swaggerapi")
}
