/*
"Generated by OpenAI's chatGPT" - w/ modifications
*/
package main

import (
	"log"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"

	"github.com/TimetoPretend54/go-chatgpt-copilot/api"
	animalMiddleware "github.com/TimetoPretend54/go-chatgpt-copilot/api/middleware"
)

func main() {
	// Create a new Echo instance
	e := echo.New()

	// Middleware
	e.Use(animalMiddleware.Logger())
	// e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	// Inject Dependencies
	dc := api.InitDependencies()

	// Load animal routes
	dc.LoadAnimalRoutes(e)

	// Info Msg
	log.Println("Example API Call: http://localhost:8081/animals/cat")
	log.Println("Swagger Docs: http://localhost:8081/swagger/")

	// Start server
	log.Fatal(e.Start(":8081"))
}
